listeners:
- query_port: 25565
  motd: '&1艾伯塔服务器'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 58956d90-38af-492a-bb22-af74b1897e1a
player_limit: -1
ip_forward: true
groups:
  BiShop:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1艾伯塔登录服务器'
    address: localhost:25575
    restricted: false
  main:
    motd: '&1艾伯塔主服务器'
    address: localhost:25585
    restricted: false
  dungeon:
    motd: '&1艾伯塔副本服务器'
    address: localhost:25595
    restricted: false
